---
- name: install pgbouncer
  apt:
    pkg: pgbouncer
    state: "{{ pgbouncer_install_state }}"
    update_cache: yes
    cache_valid_time: 3600

- name: install postgresql-client
  apt:
    pkg: postgresql-client
    state: present
  when: pgbouncer_install_psql

- name: mask default postgresql service if needed
  systemd:
    name: postgresql.service
    state: stopped
    enabled: false
    masked: true
  when: pgbouncer_mask_postgresql_service
  tags: mask

- name: Ensure needed directories exists with correct permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: postgres
    group: postgres
  loop: 
    - "{{ pgbouncer_confdir }}"
    - "{{ pgbouncer_logdir }}"
    - "{{ pgbouncer_unix_socket_dir }}"

- name: template main config file
  template:
    src: templates/pgbouncer.ini.j2
    dest: "{{ pgbouncer_confdir }}/pgbouncer.ini"
    backup: yes
    owner: postgres
    group: postgres
    mode: 0640
  notify: "{{ pgbouncer_service_state }} pgbouncer"

- name: template auth hba file
  template:
    src: templates/pgb_hba.conf.j2
    dest: "{{ pgbouncer_auth_hba_file }}"
    backup: yes
    owner: postgres
    group: postgres
    mode: 0640
  when: pgbouncer_auth_hba_file is defined and pgbouncer_hba|length > 0
  notify: "{{ pgbouncer_service_state }} pgbouncer"

- name: template database section of config file
  template:
    src: templates/pgbouncer.databases.ini.j2
    dest: "{{ pgbouncer_confdir }}/pgbouncer.databases.ini"
    backup: yes
    owner: postgres
    group: postgres
    mode: 0640
  notify: "{{ pgbouncer_service_state }} pgbouncer"
  when: pgbouncer_template_databases and pgbouncer_databases|length>0

- name: template userlist
  template:
    src: templates/userlist.txt.j2
    dest: "{{ pgbouncer_confdir }}/userlist.txt"
    backup: yes
    owner: postgres
    group: postgres
    mode: 0640
  notify: "{{ pgbouncer_service_state }} pgbouncer"
  when: pgbouncer_template_userlist and pgbouncer_users|length>0
